name: Build and Zip

on:
  push:
    branches:
      - staging
      - main

jobs:
  build-and-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Create a temporary directory
      run: mkdir temp_dist

    - name: Build project in temporary directory
      run: |
        npm install
        npm run build-temp

    - name: Inspect dist folder
      run: ls temp_dist

    - name: Zip dist contents
      run: |
        CURRENT_DATE=$(date +"%Y-%m-%d-%H-%M-%S")
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        BRANCH_NAME=$(echo $GITHUB_REF | awk -F/ '{print $3}')
        if [ "$BRANCH_NAME" == "staging" ]; then
          ZIP_NAME="$REPO_NAME-sta-$CURRENT_DATE.zip"
        elif [ "$BRANCH_NAME" == "main" ]; then
          ZIP_NAME="$REPO_NAME-prod-$CURRENT_DATE.zip"
        else
          ZIP_NAME="$REPO_NAME-$CURRENT_DATE.zip"
        fi
        cd temp_dist
        zip -r ../$ZIP_NAME .
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-artifact
        path: ${{ runner.workspace }}/$ZIP_NAME
