name: Release Notifications

on:
  release:
    types:
      - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Release Notes
        id: release_notes
        run: |
          RELEASE_NOTES=$(curl -s -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/${{ github.repository }}/releases/${{ github.event.release.id }}" | \
            jq -r '.body' | sed 's/"/\\"/g' | sed ':a;N;$!ba;s/\n/\\n/g')
          echo "::set-output name=release_notes::$RELEASE_NOTES"

      - name: Convert Markdown to Slack Format
        id: slackify_markdown
        uses: vsoch/slackify-markdown@v1
        with:
          text: ${{ steps.release_notes.outputs.release_notes }}

      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          RELEASE_NOTES: ${{ steps.slackify_markdown.outputs.text }}
        run: |
          RELEASE_NAME=$(echo "${{ github.event.release.name }}" | jq -R .)
          RELEASE_URL=$(echo "${{ github.event.release.html_url }}")

          MESSAGE="New release: $RELEASE_NAME\nRelease Notes:\n${RELEASE_NOTES}\n$RELEASE_URL"
          
          curl -X POST -H 'Content-type: application/json' --data "{'text':'$MESSAGE'}" $SLACK_WEBHOOK_URL