name: Release Notifications

on:
  release:
    types:
      - created

jobs:
  notify_slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          RELEASE_NAME=$(echo "${{ github.event.release.name }}" | jq -R .)
          RELEASE_URL=$(echo "${{ github.event.release.html_url }}")
          MESSAGE="New release: $RELEASE_NAME\nRelease URL: $RELEASE_URL"
          
          curl -X POST -H 'Content-type: application/json' --data "{'text':'$MESSAGE'}" $SLACK_WEBHOOK_URL